Traceback (most recent call last):
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/z0272571a@CAMPUS.CSIC.ES/miniconda3/envs/pyTSEB/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
south_africa_aoi.crs
south_africa_aoi_wm = south_africa_aoi.to_crs(epsg=3857)
ax = south_africa_aoi_wm.plot(figsize=(10, 10), alpha=0.5, edgecolor="k")
cx.add_basemap(ax)
ax.set_axis_off()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 4[0m
[1;32m      2[0m south_africa_aoi_wm [38;5;241m=[39m south_africa_aoi[38;5;241m.[39mto_crs(epsg[38;5;241m=[39m[38;5;241m3857[39m)
[1;32m      3[0m ax [38;5;241m=[39m south_africa_aoi_wm[38;5;241m.[39mplot(figsize[38;5;241m=[39m([38;5;241m10[39m, [38;5;241m10[39m), alpha[38;5;241m=[39m[38;5;241m0.5[39m, edgecolor[38;5;241m=[39m[38;5;124m"[39m[38;5;124mk[39m[38;5;124m"[39m)
[0;32m----> 4[0m [43mcx[49m[38;5;241m.[39madd_basemap(ax)
[1;32m      5[0m ax[38;5;241m.[39mset_axis_off()

[0;31mNameError[0m: name 'cx' is not defined

